name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules.
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            example/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Installing dependencies.
        run: yarn install
      - name: Building.
        run: yarn build
      - name: Installing examples dependencies.
        run: |
          cd example
          yarn install
      - name: Building examples.
        run: |
          cd example
          yarn build
      - name: Testing.
        run: yarn test
      - name: Testing examples.
        run: |
          cd example
          yarn test
      - name: Linting.
        run: yarn lint
      - name: Checking size.
        run: yarn size





