name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Installing dependencies.
        run: yarn install
      - name: Test and lint.
        run: yarn test
      - name: Building.
        run: yarn build
      - name: Installing examples dependencies.
        run: |
          cd example
          yarn install
      - name: Building examples.
        run: |
          cd example
          yarn build
